### ISSUE TITLE
[Feature Request] MSD/Diffusion calculation in the x,y, and z direction

### ISSUE THREAD

**Issue by pzarabadip** [bjmorgan/kinisi#13]
Hi Drew (@arm61),
We have a case where we would like to investigate the isotropic/anisotropic diffusion coefficient. I wonder if it is possible to implement such feature in the `kinisi`?
Cheers,
Pezhman

**Comment by arm61** [comment]
Hey @pzarabadip, this is definitely achievable, my suggestion is that I add a `bootstrap_param` called `dimensionality`, where the default is `'xyz' but if you give any subset of these characters, the diffusion is calculated in that subset. Thoughts are welcome?

**Comment by pzarabadip** [comment]
Thanks @arm61. It would be great and works for me. Cheers
