### ISSUE TITLE
Adding a diff.save() method to save the whole DiffusionAnalyzer object

### ISSUE THREAD

**Issue by gabkrenzer** [bjmorgan/kinisi#15]
This would be very useful to then post-process soundly.

**Comment by arm61** [comment]
This is a good idea, implementation would involve a `.save()` method and a `.load()` method for the `Analyzer` class, should be pretty straight forward to implement with `pickle`.

**Comment by arm61** [comment]
Actually it shouldn't be too mush to have `as_dict` and `from_dict` methods that can be dumped to JSON.

**Comment by arm61** [comment]
Hmm. It is looking like it is more work than I expected to have json serialisation (not impossible though). In the meantime, I recommending pickling your own objects (https://pythonexamples.org/python-pickle-class-object/).

**Comment by arm61** [comment]
I have a potential solution which writes to HDF5 files. Happy to hear thoughts on the PR

**Comment by arm61** [comment]
I have merged this solution. It will be part of a future `0.3.10` release in the coming weeks.
