### ISSUE TITLE
Implementation of ase's parser (instead of pymatgen's one)

### ISSUE THREAD

**Issue by dembart** [bjmorgan/kinisi#22]
Hello, 

I highly recommend switching to ase.io.read method for reading trajectories instead of pymatgen's Xdatcar. It is an order of magnitude faster for relatively long trajectories (~100,000 ionic steps) in comparison to pymatgen.

**Comment by bjmorgan** [comment]
Ideally both I guess, to cover both workflow ecosystems.

**Comment by arm61** [comment]
Yeah, this is something that we plan to add in the future. Thanks for bringing attention to it!
