### ISSUE TITLE
Support for ASE trajectory objects

### ISSUE THREAD

**Issue by alexsquires** [bjmorgan/kinisi#31]
Any plans to support ASE trajectory objects in the parsing functionality? https://wiki.fysik.dtu.dk/ase/ase/io/trajectory.html#trajectory

In principle, you can get at it from `pymatgen.io.ase.AseAtomsAdaptor` and then work with the pymatgen parser, but that can be quite a large computational overhead.

If it's not something you've considered, is it something you'd be interested in a contribution for?

**Comment by alexsquires** [comment]
I've just seen this was mentioned in #22 - at least I'm not the only one.

**Comment by arm61** [comment]
I was just about to link that previous issue. 

It is definitely something I want to support. But I just haven’t found the time to add it. Given your more experienced with ase, I would be happy to get a contribution (I can obviously help with your understanding of what kinisi expects) and it would save me time!

**Comment by alexsquires** [comment]
I'm on it. I'll come back with a draft when it's ready

**Comment by alexsquires** [comment]
draft in #32
