### ISSUE TITLE
misleading doc string

### ISSUE THREAD

**Issue by alexsquires** [bjmorgan/kinisi#33]
```
    def save(self, filename: str):
        """
        Save the Analyzer object as a HDF5 file.

        :param filename: Name for the file, no file extension is required and if one if given it is replaced with .hdf.
        """
```

This doc strings is explicit in saying no extension is required, but if .hdf is not given, it errors out. I considered pushing a fix but then was not sure what the intended behaviour is.

**Comment by arm61** [comment]
On reading this issue, I was also confused. I thought that I had included the behaviour to if another file extension (or no extension) is given then it will automatically make it `.hdf` but I see now that that isn't the case. I am happy to take a PR that either fixes the docstring or adds functionality (whichever you think is more intuitive).
