### ISSUE TITLE
No support for NPT simulations

### ISSUE THREAD

**Issue by arm61** [bjmorgan/kinisi#39]
Currently, `kinisi` only supports NVT simulations (because in the parser just the first lattice parameters are used). It should be a pretty straightforward fix.

**Comment by bjmorgan** [comment]
Is this also still true for pymatgen? 🤔

**Comment by arm61** [comment]
Not according to this docstring https://github.com/materialsvirtuallab/pymatgen-analysis-diffusion/blob/e376e2dd1c0a5e8fc3e6fcd37555aee679b2c85a/pymatgen/analysis/diffusion/analyzer.py#L199

**Comment by arm61** [comment]
It was noted by @jd15489 that this isn't as simple as it seems to be. https://pubs.acs.org/doi/10.1021/acs.jctc.3c00308#:~:text=In%20constant%2Dpressure%20(NPT),the%20box%20thereby%20get%20rescaled.
