### ISSUE TITLE
suggestion for CONTRIBUTING.md

### ISSUE THREAD

**Issue by lamdalamda** [bjmorgan/kinisi#40]
Here:
```
3. Install your local copy into a virtualenv. Assuming you have virtualenvwrapper installed, this is how you set up your fork for local development::

    $ mkvirtualenv kinisi
    $ cd kinisi/
    $ python setup.py develop
```
I couldn't find the setup.py (is it because I use conda instead of mkvirtualenv?), I guess it shall be installed in this way
```
pip install .[dev]
```

**Comment by bjmorgan** [comment]
@arm61 it looks like these instructions are outdated since you changed the build system to use `pyproject.toml`?

**Comment by arm61** [comment]
Yeah I have just fixed it. @lamdalamda can you check that the contributing guidelines make sense now?

**Comment by lamdalamda** [comment]
Looks great! Thank you for your instant reply @arm61 @bjmorgan
