### ISSUE TITLE
Put "Methodology" to the main page

### ISSUE THREAD

**Issue by dengzeyu** [bjmorgan/kinisi#42]
There is a very good description of methodology "https://kinisi.readthedocs.io/en/latest/methodology.html", however it's hidden in the documentation. It would be nice if it can be easily accessible from the main page.

**Comment by dengzeyu** [comment]
Just for tracking - this issue is related to the joss submission: https://github.com/openjournals/joss-reviews/issues/5984#issuecomment-1793653579

**Comment by arm61** [comment]
I have returned this to the homepage as of https://github.com/bjmorgan/kinisi/commit/28be82680216bdc6bcf24ca77a4f9d618393ae41
