### ISSUE TITLE
Compatibility with Pymatgen in documentation

### ISSUE THREAD

**Issue by dengzeyu** [bjmorgan/kinisi#43]
There is some compatility issue with pymatgen in documentation page: 
https://kinisi.readthedocs.io/en/latest/pymatgen.html

I'm using pymatgen 2023.10.11
```
ModuleNotFoundError: No module named 'pymatgen.analysis.diffusion'
```

**Comment by dengzeyu** [comment]
Just for tracking - this issue is related to the joss submission: https://github.com/openjournals/joss-reviews/issues/5984#issuecomment-1793653579

**Comment by arm61** [comment]
@bjmorgan Can you open a separate issue for the error bars thing?

@dengzeyu I have added the following commit (https://github.com/bjmorgan/kinisi/commit/28be82680216bdc6bcf24ca77a4f9d618393ae41) that explains that there is a different installation approach to build the documentation.
