### ISSUE TITLE
Error bars in the docs

### ISSUE THREAD

**Issue by arm61** [bjmorgan/kinisi#45]
It would be nice to update the pymatgen docs page so that the “error bars” plot notes the distinction between the expected variance in the observed MSD and the posterior predictive MSD distribution.

**Comment by arm61** [comment]
In https://github.com/bjmorgan/kinisi/commit/81a861c3703d19d6197a6824dce4e65ed6b93587 I have updated the text to say the variances in the *observed* MSDs. I think this this is plot that @bjmorgan was referring to but at this point in the docs, there is no posterior to generate a posterior predictive from so I think it is confusing to mention this.

**Comment by bjmorgan** [comment]
That makes sense. “Estimated variances in observed MSDs” is more precise than “error bars”.
