### ISSUE TITLE
Use of max(NGP) in docs can encourage poor practice.

### ISSUE THREAD

**Issue by bjmorgan** [bjmorgan/kinisi#46]
The docs talk about using the maximum in the non-Gaussian parameter as an indicator of "the start of the diffusive regime". e.g., https://kinisi.readthedocs.io/en/latest/vasp_dj.html.
This is not necessarily the case, and can encourage users to blindly use the max(NGP) as the start of their fitting regime, withouth looking at their data.
I suggest we revise the docs so that we do not imply that max(NGP) can always be used as a sensible fitting start-point.

**Comment by arm61** [comment]
The very next paragraph says "It appears that the non-Gaussian parameter does not accurately predict the start of the diffusive regime for this example".

**Comment by bjmorgan** [comment]
I think this is potentially opaque to readers. People will skim the page and read that in the first usage the max-NGP *is* an indicator of the start of the diffusive regime, and run with it.

**Comment by bjmorgan** [comment]
Personally, I would probably take max-NGP out of this part of the docs.

**Comment by arm61** [comment]
I am not opposed to removing the mention of the max-NGP.

**Comment by bjmorgan** [comment]
> I am not opposed to removing the mention of the max-NGP.

This makes sense to me. Plotting max-NGP and then having to make a judgement call over whether it is useful seems no more rigorous than just stating where the start of the fitting regime is (especially in the context of this docs page).

**Comment by arm61** [comment]
Resolved in https://github.com/bjmorgan/kinisi/commit/683531f95e67d7c358723334a540f64edffec4da
