### ISSUE TITLE
Subtract drift/center of mass during MSD calculation

### ISSUE THREAD

**Issue by dembart** [bjmorgan/kinisi#57]
Hello,

What do you think, is subtracting the drift of the entire system a necessary feature when calculating MSD? Seems to be an important step for the non-periodic systems, but not sure about 3D periodicity. It was somehow implemented in pymatgen's analyzer (using center of the geometry of a non-mobile framework ions) and maybe you can add similar feature in your package

**Comment by arm61** [comment]
We already perform a drift correction. @jd15489 can comment better but I believe that the drift of everything that isn't the identified `specie` is corrected for.

**Comment by dembart** [comment]
Yeah, you are right. Was not expecting the feature is hidden in parser.py. Sorry for disturbing!
