### ISSUE TITLE
Diffusion coefficient Units

### ISSUE THREAD

**Issue by vikas41299** [bjmorgan/kinisi#65]
Hello, 

Please let me confirm, that the units for diffusion coefficient are cm^2/s if we extract the data from XDATCAR from VASP MD simulations.
If I compare the diffusion coefficient with VASPKIT data (which generates in terms of cm^2/s), then it seems that kinsi produces D in units of m^2/s or vice versa.  Below, I provide the value of D from VASPKIT and KINSI at similar temperature: 
   VASPKIT: 0.1012E-04
   KINSI: 9.795032526434394e-09
   
   Thankyou!

**Comment by arm61** [comment]
I am reasonably sure that the diffusion coefficient units in kinisi are cm<sup>2</sup>/s when extracted from an XDATCAR file; this is mentioned in the documentation (https://kinisi.readthedocs.io/en/latest/faq.html#faq). 

My understanding is that the XDATCAR uses the units of angstrom and femtoseconds. When the file is parsed into kinisi, this is converted to kinisi’s internal units of angstrom and picoseconds (this conversion is performed on [line 437 of the `parser.py`](https://github.com/bjmorgan/kinisi/blob/5912dc92bac0f9f9afee7fe9f06f1847beb2fcb6/kinisi/parser.py#L437)). The linear fit is then determined in these units (so that the unit of the gradient is Å<sup>2</sup>/ps), and the diffusion coefficient found in units of cm<sup>2</sup>/s by multiplying by 10000 &times; *2d*, where *2d* is for the dimensionality of the diffusion and the 10000 takes us from Å<sup>2</sup>/ps to cm<sup>2</sup>/s (see this [line 436 of `diffusion.py`](https://github.com/bjmorgan/kinisi/blob/5912dc92bac0f9f9afee7fe9f06f1847beb2fcb6/kinisi/diffusion.py#L436) for that conversion). 

As for comparison to VASPKIT, I cannot comment. The MSD/diffusion functionality of this software is (1) not clearly documented  (the only mention of MSD I can find on their documentation is under [molecular dynamics processes](https://vaspkit.com/tutorials.html#molecular-dynamics-process) and makes no mention of units) and (2) closed source (the software appears to only be available as a binary so I cannot determine what the code is doing to reach the outputs that you have obtained. 

Hopefully, that all helps. If you have any further questions, please do not hesitate to reach out.

**Comment by niuniu800** [comment]
Hello, when I call the kinish library and output the MSD data, I find that it is not output according to the settings in my script. What is the problem? **The script is as follows:**
import numpy as np
from kinisi.analyze import DiffusionAnalyzer
import matplotlib.pyplot as plt

# 设置随机种子
np.random.seed(6)

# 定义参数
params = {
    'specie': 'Na',        # 选择要计算的物种
    'time_step': 2.0,     # 模拟的时间步长（单位：飞秒）
    'step_skip': 100,      # 数据存储的间隔（每50步存储一次）
    'progress': False      # 是否显示进度
}
u_params = {'progress': False}  # 不确定性参数

output_path = r'D:\Desktop\jisuan\1\Na_MSD_data.txt'
# 从XDATCAR文件读取数据并计算MSD
msd = DiffusionAnalyzer.from_file(r'D:\Desktop\jisuan\1\XDATCAR_new', parser_params=params, uncertainty_params=u_params)

# 将MSD数据写入文本文件
with open(output_path, 'w', encoding='utf-8') as f:
    f.write("Na元素的MSD数据（含不确定性）:\n")
    for dt, msd_val, msd_std in zip(msd.dt, msd.msd, msd.msd_std):
        f.write(f"Δt = {dt} ps: MSD = {msd_val} Å^2 ± {msd_std} Å^2\n")

print(f"MSD数据已保存到 {output_path}")
# 绘制MSD与时间步长的关系
plt.errorbar(msd.dt, msd.msd, yerr=msd.msd_std, fmt='o')
plt.ylabel('MSD (Å²)')
plt.xlabel(r'$\Delta t$ (fs)')
plt.title('Mean Squared Displacement (MSD)')
plt.grid()
plt.show()
**The output is as follows:**
Na元素的MSD数据（含不确定性）:
Δt = 0.2 ps: MSD = 0.00026416731115462935 Å^2 ± 2.78711728854251e-07 Å^2
Δt = 50.6 ps: MSD = 1.0392314504224172 Å^2 ± 0.031238399822589972 Å^2
Δt = 101.2 ps: MSD = 1.2621070822090246 Å^2 ± 0.07510910456074009 Å^2
Δt = 151.8 ps: MSD = 1.5180492657937783 Å^2 ± 0.1281458991608184 Å^2
Δt = 202.4 ps: MSD = 1.8730244950925623 Å^2 ± 0.189536987993384 Å^2
Δt = 253.0 ps: MSD = 2.1463244243990656 Å^2 ± 0.24712970191985767 Å^2
Δt = 303.6 ps: MSD = 2.4773024320971486 Å^2 ± 0.3093088932444769 Å^2
Δt = 354.2 ps: MSD = 2.7647280125824367 Å^2 ± 0.36426460657581694 Å^2
Δt = 404.8 ps: MSD = 3.057293370515228 Å^2 ± 0.42342886803006646 Å^2
Δt = 455.40000000000003 ps: MSD = 3.3903891021634283 Å^2 ± 0.47756278168154126 Å^2
Δt = 506.0 ps: MSD = 3.6371280507006065 Å^2 ± 0.5320978068665255 Å^2
Δt = 556.6 ps: MSD = 3.961643468858167 Å^2 ± 0.5933544392243943 Å^2
Δt = 607.2 ps: MSD = 4.2795153224202735 Å^2 ± 0.6545294397937017 Å^2
Δt = 657.8000000000001 ps: MSD = 4.5599090308006245 Å^2 ± 0.7152942011342398 Å^2
Δt = 708.4 ps: MSD = 4.880429563012187 Å^2 ± 0.7750161717746094 Å^2
Δt = 759.0 ps: MSD = 5.191656122878462 Å^2 ± 0.8409761230546329 Å^2
Δt = 809.6 ps: MSD = 5.505856843982649 Å^2 ± 0.9146806987752679 Å^2
Δt = 860.2 ps: MSD = 5.852281361408027 Å^2 ± 0.9872053365496616 Å^2
Δt = 910.8000000000001 ps: MSD = 6.154828201413918 Å^2 ± 1.0474209692277634 Å^2
Δt = 961.4 ps: MSD = 6.493157141929578 Å^2 ± 1.1182915075702553 Å^2
Δt = 1011.8000000000001 ps: MSD = 6.772825014790365 Å^2 ± 1.1831315768260247 Å^2
Δt = 1062.4 ps: MSD = 7.125077599736805 Å^2 ± 1.2578744733155263 Å^2
Δt = 1113.0 ps: MSD = 7.50208486756542 Å^2 ± 1.3413649353446189 Å^2
Δt = 1163.6000000000001 ps: MSD = 7.864767793329171 Å^2 ± 1.4367060926701483 Å^2
Δt = 1214.2 ps: MSD = 8.24392121412096 Å^2 ± 1.5508474033265514 Å^2
Δt = 1264.8 ps: MSD = 8.63152147126989 Å^2 ± 1.6609296500626698 Å^2
Δt = 1315.4 ps: MSD = 9.01048936516387 Å^2 ± 1.7690067456810616 Å^2
Δt = 1366.0 ps: MSD = 9.4114695216321 Å^2 ± 1.8758725564850793 Å^2
Δt = 1416.6000000000001 ps: MSD = 9.792724239395685 Å^2 ± 1.982346428925623 Å^2
Δt = 1467.2 ps: MSD = 10.20983598461965 Å^2 ± 2.087790314500308 Å^2
Δt = 1517.8 ps: MSD = 10.569083600743697 Å^2 ± 2.189525911003101 Å^2
Δt = 1568.4 ps: MSD = 10.936705619984515 Å^2 ± 2.2899649467234457 Å^2
Δt = 1619.0 ps: MSD = 11.336298166954593 Å^2 ± 2.391130117067364 Å^2
Δt = 1669.6000000000001 ps: MSD = 11.680365401283973 Å^2 ± 2.485877825476973 Å^2
Δt = 1720.2 ps: MSD = 12.08550250335284 Å^2 ± 2.586194086055586 Å^2
Δt = 1770.8 ps: MSD = 12.507338378968457 Å^2 ± 2.6913414942480016 Å^2
Δt = 1821.4 ps: MSD = 12.905048214502001 Å^2 ± 2.7959154060756375 Å^2
Δt = 1872.0 ps: MSD = 13.332382952420408 Å^2 ± 2.912174179307137 Å^2
Δt = 1922.6000000000001 ps: MSD = 13.746924010689614 Å^2 ± 3.02232355353821 Å^2
Δt = 1973.2 ps: MSD = 14.200311166207694 Å^2 ± 3.123833090276567 Å^2
Δt = 2023.6000000000001 ps: MSD = 14.641313191047079 Å^2 ± 3.231147876928519 Å^2
Δt = 2074.2 ps: MSD = 15.094522292375348 Å^2 ± 3.3416220291791126 Å^2
Δt = 2124.8 ps: MSD = 15.559008260871153 Å^2 ± 3.451697653066896 Å^2
Δt = 2175.4 ps: MSD = 15.982377154046493 Å^2 ± 3.560898151514889 Å^2
Δt = 2226.0 ps: MSD = 16.42252534770732 Å^2 ± 3.67223989927224 Å^2
Δt = 2276.6 ps: MSD = 16.895723466606697 Å^2 ± 3.7939820044005916 Å^2
Δt = 2327.2000000000003 ps: MSD = 17.30899129736661 Å^2 ± 3.9029642567926564 Å^2
Δt = 2377.8 ps: MSD = 17.755594170291968 Å^2 ± 4.027042412940208 Å^2
Δt = 2428.4 ps: MSD = 18.183747074966206 Å^2 ± 4.12706669566324 Å^2
Δt = 2479.0 ps: MSD = 18.656059967086954 Å^2 ± 4.234997876824545 Å^2
Δt = 2529.6 ps: MSD = 19.138289101958833 Å^2 ± 4.348059344899736 Å^2
Δt = 2580.2000000000003 ps: MSD = 19.61542118562069 Å^2 ± 4.445965496112639 Å^2
Δt = 2630.8 ps: MSD = 20.101620965083605 Å^2 ± 4.553239547327412 Å^2
Δt = 2681.4 ps: MSD = 20.687910595994094 Å^2 ± 4.685225979729197 Å^2
Δt = 2732.0 ps: MSD = 21.270551087529363 Å^2 ± 4.82644679402725 Å^2
Δt = 2782.6 ps: MSD = 21.76688107933484 Å^2 ± 4.933406330715042 Å^2
Δt = 2833.2000000000003 ps: MSD = 22.25638046362578 Å^2 ± 5.036231633096008 Å^2
Δt = 2883.8 ps: MSD = 22.714059822303962 Å^2 ± 5.137365749341592 Å^2
Δt = 2934.4 ps: MSD = 23.19155546517304 Å^2 ± 5.23804384797368 Å^2
Δt = 2985.0 ps: MSD = 23.67456609712318 Å^2 ± 5.352744674539888 Å^2
Δt = 3035.4 ps: MSD = 24.10590257936388 Å^2 ± 5.455835268019857 Å^2
Δt = 3086.0 ps: MSD = 24.590326776651242 Å^2 ± 5.554014963355482 Å^2
Δt = 3136.6 ps: MSD = 25.06594149689662 Å^2 ± 5.6653387561131385 Å^2
Δt = 3187.2000000000003 ps: MSD = 25.67604366664514 Å^2 ± 5.8007830096111315 Å^2
Δt = 3237.8 ps: MSD = 26.155873768084486 Å^2 ± 5.914149695407706 Å^2
Δt = 3288.4 ps: MSD = 26.709831297641582 Å^2 ± 6.024992995723785 Å^2
Δt = 3339.0 ps: MSD = 27.281403082834416 Å^2 ± 6.1447498886283585 Å^2
Δt = 3389.6 ps: MSD = 27.771180864236346 Å^2 ± 6.2468703750520325 Å^2
Δt = 3440.2000000000003 ps: MSD = 28.285781490777335 Å^2 ± 6.319534110685934 Å^2
Δt = 3490.8 ps: MSD = 28.750331452437017 Å^2 ± 6.386602201873072 Å^2
Δt = 3541.4 ps: MSD = 29.414395592995124 Å^2 ± 6.478584844158102 Å^2
Δt = 3592.0 ps: MSD = 29.909855748616305 Å^2 ± 6.554832473811229 Å^2
Δt = 3642.6 ps: MSD = 30.435469683896997 Å^2 ± 6.638578551222163 Å^2
Δt = 3693.2000000000003 ps: MSD = 30.940133408255555 Å^2 ± 6.728302677928593 Å^2
Δt = 3743.8 ps: MSD = 31.48418357219736 Å^2 ± 6.826720606825783 Å^2
Δt = 3794.4 ps: MSD = 31.935006040377715 Å^2 ± 6.907201401825879 Å^2
Δt = 3845.0 ps: MSD = 32.49725013301616 Å^2 ± 7.017353029202918 Å^2
Δt = 3895.6 ps: MSD = 33.08531502919015 Å^2 ± 7.1200129348490675 Å^2
Δt = 3946.2000000000003 ps: MSD = 33.78416149143344 Å^2 ± 7.204060014395162 Å^2
Δt = 3996.8 ps: MSD = 34.378530733640616 Å^2 ± 7.266171722509768 Å^2
Δt = 4047.2000000000003 ps: MSD = 34.9147266313544 Å^2 ± 7.342616207727946 Å^2
Δt = 4097.8 ps: MSD = 35.587237040792175 Å^2 ± 7.442339631878433 Å^2
Δt = 4148.4 ps: MSD = 36.14392853134677 Å^2 ± 7.549891526892581 Å^2
Δt = 4199.0 ps: MSD = 36.718925235735824 Å^2 ± 7.643890957687814 Å^2
Δt = 4249.6 ps: MSD = 37.36542946529698 Å^2 ± 7.775356726570111 Å^2
Δt = 4300.2 ps: MSD = 37.953480287406784 Å^2 ± 7.84616483193678 Å^2
Δt = 4350.8 ps: MSD = 38.58288727766979 Å^2 ± 7.938436112531952 Å^2
Δt = 4401.400000000001 ps: MSD = 39.22555328830208 Å^2 ± 8.009744853122026 Å^2
Δt = 4452.0 ps: MSD = 39.837255496954256 Å^2 ± 8.064581587559099 Å^2
Δt = 4502.6 ps: MSD = 40.62568743049962 Å^2 ± 8.159898118479509 Å^2
Δt = 4553.2 ps: MSD = 41.92251162386656 Å^2 ± 8.278730798104935 Å^2
Δt = 4603.8 ps: MSD = 42.8812687782366 Å^2 ± 8.40152849226212 Å^2
Δt = 4654.400000000001 ps: MSD = 43.58228822260366 Å^2 ± 8.528120011322915 Å^2
Δt = 4705.0 ps: MSD = 43.82935342509425 Å^2 ± 8.558630882395263 Å^2
Δt = 4755.6 ps: MSD = 43.97821247288957 Å^2 ± 8.55349281295251 Å^2
Δt = 4806.2 ps: MSD = 43.28223734811893 Å^2 ± 8.528478858162137 Å^2
Δt = 4856.8 ps: MSD = 42.45150935084903 Å^2 ± 8.53076657725538 Å^2
Δt = 4907.400000000001 ps: MSD = 43.572111823374165 Å^2 ± 8.988242800818368 Å^2
Δt = 4958.0 ps: MSD = 42.82223931680814 Å^2 ± 8.989495686697225 Å^2
Δt = 5008.6 ps: MSD = 41.10460314487231 Å^2 ± 8.72907846846977 Å^2
**What is causing this issue? Is it not possible to modify the data storage interval?**

**Comment by arm61** [comment]
@niuniu800, could you possibly open a new issue with this problem instead of adding to a closed issue? 

Could you please also include what you expect the output to be?
