### ISSUE TITLE
 How can I output the Mean Squared Displacement (MSD) in the x, y, and z directions separately?

### ISSUE THREAD

**Issue by niuniu800** [bjmorgan/kinisi#80]
**Hello, I would like to know how to output the Mean Squared Displacement (MSD) in each direction within a script. Here is my script:**
import numpy as np
from kinisi.analyze import DiffusionAnalyzer
import matplotlib.pyplot as plt

np.random.seed(6)

# 定义参数
params = {
    'specie': 'Na',         # 选择要计算的物种
    'time_step': 2.0,       # 模拟的时间步长（单位：飞秒）
    'step_skip': 1,         # 数据存储的间隔（每50步存储一次）
    'progress': False       # 是否显示进度
}
u_params = {'progress': False}  # 不确定性参数

output_path = r'D:\Desktop\jisuan\1\Na_MSD_data.txt'

msd = DiffusionAnalyzer.from_file(r'D:\Desktop\jisuan\1\XDATCAR_new', parser_params=params, uncertainty_params=u_params)

diffusion_coefficient = np.polyfit(msd.dt, msd.msd, 1)[0] / 6

with open(output_path, 'w', encoding='utf-8') as f:
    f.write("Na元素的MSD数据（含不确定性）:\n")
    for dt, msd_val, msd_std, msd_x, msd_y, msd_z in zip(msd.dt, msd.msd, msd.msd_std, msd.msd_x, msd.msd_y, msd.msd_z):
        f.write(f"Δt = {dt} ps: MSD = {msd_val} Å^2 ± {msd_std} Å^2\n")
        f.write(f"   MSD_x = {msd_x} Å^2, MSD_y = {msd_y} Å^2, MSD_z = {msd_z} Å^2\n")
    f.write(f"\n扩散系数 D = {diffusion_coefficient:.5f} Å^2/ps\n")

print(f"MSD数据和扩散系数已保存到 {output_path}")

plt.errorbar(msd.dt, msd.msd, yerr=msd.msd_std, fmt='o', label='总MSD')
plt.ylabel('MSD (Å²)')
plt.xlabel(r'$\Delta t$ (ps)')
plt.title('平均平方位移 (MSD)')
plt.grid()
plt.legend()

plt.figure()
plt.plot(msd.dt, msd.msd_x, 'r-', label='MSD_x')
plt.plot(msd.dt, msd.msd_y, 'g-', label='MSD_y')
plt.plot(msd.dt, msd.msd_z, 'b-', label='MSD_z')
plt.ylabel('MSD (Å²)')
plt.xlabel(r'$\Delta t$ (ps)')
plt.title('每个方向的平均平方位移 (MSD)')
plt.grid()
plt.legend()
plt.show()

**After running, the display shows:**
warnings.warn(
Traceback (most recent call last):
  File "E:\pycharm-community\learn\python-learning\MSD\msd_new.py", line 27, in <module>
    for dt, msd_val, msd_std, msd_x, msd_y, msd_z in zip(msd.dt, msd.msd, msd.msd_std, msd.msd_x, msd.msd_y, msd.msd_z):
                                                                                       ^^^^^^^
AttributeError: 'DiffusionAnalyzer' object has no attribute 'msd_x'

**Comment by arm61** [comment]
Thanks for your interest in `kinisi`. The short answer is that you need to run `kinisi` individually using the `'dimension'` keyword argument to get the MSD in each dimension. For example to calculate in the `'x'` dimension would make your code become: 
```
params = {
    'specie': 'Na',
    'time_step': 2.0, 
    'step_skip': 1, 
    'progress': False 
}
u_params = {
    'progress': False,
    'dimension': 'x'
} 

output_path = r'D:\Desktop\jisuan\1\Na_MSD_data.txt'

msd = DiffusionAnalyzer.from_file(r'D:\Desktop\jisuan\1\XDATCAR_new', parser_params=params, uncertainty_params=u_params)
```

I want to point out that in your current code, you are still obtaining a sub-optimal estimate of the diffusion coefficient (i.e., `diffusion_coefficient = np.polyfit(msd.dt, msd.msd, 1)[0] / 6`). The purpose of `kinisi` is that it offers an optimal estimate of the diffusion coefficient. 

I suggest you look at the documentation to see how you obtain the diffusion coefficient with `kinisi` (https://kinisi.readthedocs.io/en/latest/vasp_d.html). Furthermore, if you are interested in the methodology to obtain this optimal estimate, a preprint discusses this in detail (https://arxiv.org/abs/2305.18244).
