### ISSUE TITLE
Time step length

### ISSUE THREAD

**Issue by w-yuxuan** [bjmorgan/kinisi#81]
Dear Kinisi developers,
Thank you for making this amazing software that helped me tons! 

under class kinisi.parser.Parser:
"time_step (float) – Time step, in picoseconds, between steps in trajectory."

I found that when my VASP run have 1 fs between steps (POTIM=1), setting time_step=1 instead of 1E-3 gave the correct x axis value (∆t/ps)
when I do:
plt.errorbar(diff.dt, diff.msd, diff.msd_std)
plt.ylabel('MSD/Å$^2$')
plt.xlabel(r'$\Delta t$/ps')

 I'm probably doing something wrong, or is the time_step indeed in [fs]?
 
 Thank you so much again!

**Comment by arm61** [comment]
Thanks for using kinisi. 

It is the case that when you read in the VASP inut file, the input units are fs. But then kinisi will convert this to ps. This is explained here: https://kinisi.readthedocs.io/en/latest/faq.html

Hopefully that makes sense. If not please reopen the issue.

**Comment by w-yuxuan** [comment]
Thank you Dr. McCluskey for the quick response.  Just to make sure I
understand the text correctly, for my case, I should keep the time_step as
1, and if I want every step to be used for the diffusion calculation:

step_skip': 1 ?


Thank you!

**Comment by arm61** [comment]
For you, the `'time_step'` should be `1`. The `'step_skip'` should be the printing output frequency of your MD trajectory. I believe that this is called `NBLOCK` in VASP.

**Comment by w-yuxuan** [comment]
Thanks for the clarification!
